import './globals.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import Header from "@/components/Header/Header";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body className={inter.className + ' bg-gray-100'}>
    <Header/>
    <div
      className="flex items-center justify-center bg-gray-100 min-h-[calc(100vh_-_60px)] px-6 sm:px-24 md:px-32 lg:px-42 py-5"
    >
      {children}
    </div>
    </body>
    </html>
  );
}
